# Travis Continuous Integration Configuration File
sudo: required
dist: trusty
language: generic

notifications:
  email:
    recipients:
      - lars.tingelstad@ntnu.no
    on_success: change #[always|never|change] # default: change
    on_failure: change #[always|never|change] # default: always

env:
  global:
    - UPSTREAM_WORKSPACE=file
    - ROSINSTALL_FILENAME=kuka_eki.rosinstall
    - ROS_PARALLEL_TEST_JOBS=-j1
  matrix:
    - ROS_DISTRO=kinetic ROS_REPO=ros-shadow-fixed

install:
  - git clone https://github.com/ros-industrial/industrial_ci.git .ci_config
script:
  - .ci_config/travis.sh